### ISSUE TITLE
内置节点rect，设置label，label文字不显示

### ISSUE THREAD

**Issue by WenHua39** [antvis/F6#128]
内置节点rect，设置label，label文字不显示，
内置节点modelRect与image，的document.getByElementId('container')creatImage不存在问题现在有解决方式么?

**Comment by ICMI** [comment]
这个最好发下相关的代码片段，看起来不是已知问题，需要复现

**Comment by WenHua39** [comment]
内置节点rect，设置label，label文字不显示，这个rect的style生效了，但是label不显示出来
                    return group.addShape('rect', {
                        label: '123',
                        x: 10,
                        y: 10,
                        labelCfg: {
                          style: {
                            fill: '#000',
                            fontSize: 18,
                          },
                          position: 'bottom',
                        },
                        attrs: {
                            fill: '#FFF',
                            radius: 15,
                            width: cfg.size[0],
                            height: cfg.size[1],
                            overflow: 'visible',
                        },
                        // draggable: true,
                        // must be assigned in F6 3.3 and later versions. it can be any value you want
                        name: 'rect-shape',
                        // zIndex: 1,
                    });

**Comment by ICMI** [comment]
这个是你这边理解错了，添加text是这样添加的， [参见](https://f6.antv.vision/zh/docs/api/shapeProperties#%E6%96%87%E6%9C%AC-text)
这里有两个概念，[元素](https://f6.antv.vision/zh/docs/api/Items/itemProperties)和[图形](https://f6.antv.vision/zh/docs/api/shapeProperties)，元素由图形绘制出来。比如上面你定义的一个元素，由rect和text两个图形组成。

**Comment by ICMI** [comment]
modelRect 问题[参考 ](https://github.com/antvis/F6/issues/127#issuecomment-1055391969)

**Comment by WenHua39** [comment]
好的，感谢
