### ISSUE TITLE
微信小程序中无法缩放移动

### ISSUE THREAD

**Issue by Mrchen128** [antvis/F6#141]
微信小程序中无法缩放移动，触摸事件触发了，但是没有任何缩放效果

**Comment by ICMI** [comment]
微信小程序事件需要手动外部触发， 参考： https://github.com/antvis/F6/blob/54c1ea18627768b01972a99f8d829165bd5cc27d/packages/examples-wx/package-elements/pages/elements/circle/index.js#L53

**Comment by Mrchen128** [comment]
解决了，微信里面的传参需要e.detail，支付宝好像不需要
