### ISSUE TITLE
uniapp mindmap文字换行问题

### ISSUE THREAD

**Issue by homestylew** [antvis/F6#143]
mindmap使用文字行后，边的长度变得非常长，看着很怪异，不知道是不是自己写错了。
测试链接：[https://codesandbox.io/s/heuristic-volhard-zibu9r?file=/index.html](url)

**Comment by ICMI** [comment]
验证了下，确实是文本换行后宽度计算的问题，预计本周内修复

**Comment by homestylew** [comment]
> 

还有高度，猜测代码里计算的文本的length

**Comment by homestylew** [comment]
> 验证了下，确实是文本换行后宽度计算的问题，预计本周内修复

还有高度，猜测代码计算的是文本的长度

**Comment by oneness0** [comment]
不维护了？

**Comment by ICMI** [comment]
> 

在维护的，不过投入精力会少
--------
这个issue后续和同学在钉钉上沟通了，因为依赖的树图布局，默认计算文本宽度方式不支持多行，但可以外部传入覆盖原本方式，故不做处理
