### ISSUE TITLE
h5 layout dagre 报错 The layout method: 'dagre' does not exist! Please specify it first.

### ISSUE THREAD

**Issue by jzstkarol** [antvis/F6#146]
layout: {
    type: "dagre",
    ranksep: 100,
    nodesep: 30,
    rankdir: "LR"
  },

**Comment by jzstkarol** [comment]
![image](https://user-images.githubusercontent.com/95728168/186064754-80bd6ff7-dacb-482f-a955-1e2109de317e.png)

**Comment by ICMI** [comment]
https://github.com/antvis/F6/blob/c2b2576eb936ac3664535ff70c3dd3e8b805e5ee/packages/f6/stories/g-force/index.tsx#L3

参考这个力导的使用，需要import后，register下

**Comment by jzstkarol** [comment]
秒回 感谢！
