### ISSUE TITLE
Pages/GeneralGraph/dagreConfigurationTranslate

### ISSUE THREAD

**Issue by hungwii** [antvis/F6#20]
设置了fitView,fitViewPadding,但是无法把图限制在可视区内

![image](https://user-images.githubusercontent.com/40631274/122534138-d2f47b00-d054-11eb-915d-b409a1fd484b.png)

**Comment by openwayne** [comment]
每次操作完layout后，需单独调用fitview进行处理，可以讨论是否有必要设计自动fitview机制
