### ISSUE TITLE
微信小程序真机不能发布，提示代码包大小超过2M了

### ISSUE THREAD

**Issue by dfengwji** [antvis/F6#25]
代码还能压缩吗？ demo真机发布提示超过2M。

**Comment by openwayne** [comment]
> 代码还能压缩吗？ demo真机发布提示超过2M。
应该只有500多k，压缩后120-130k左右，可以发个截图看下不？

**Comment by openwayne** [comment]
细节可以参考 https://f6.antv.vision/zh/docs/manual/tutorial/mini/wechat 有完整的流程

**Comment by openwayne** [comment]
可以参考以上文档中，删除不必要的npm包

**Comment by openwayne** [comment]
建议使用微信/支付宝小程序分包
