### ISSUE TITLE
增加 Plugin: Timebar

### ISSUE THREAD

**Issue by openwayne** [antvis/F6#28]

**Comment by ICMI** [comment]
1. Timebar场景分析，是否需要提供和G6差异化的场景？
  a. 交互/流程：
    ⅰ. 增加/减少/拖动框选范围  
    ⅱ. 播放 暂停 快进 播放速度 范围/单点选择
  b. UI
    ⅰ. simple
    ⅱ. trend
    ⅲ. tick
    ⅳ. 播放条
  c. 问题和差异
    ⅰ. 考虑横竖屏，竖屏可以把滑动条搞到侧面去，width>height认为是横屏
    ⅱ. 考虑滑块大小，搞大
    ⅲ. 调整速度滑块先不搞，等想到了新样式
2. 实现思路
  a. 三种模式，但是主要流程基本一致，把流程逻辑抽出来，配合三套UI组件
  b. 交互比较多，而且操作UI部分有交集，比较容易乱，组合成一个组件统筹
  c. 扩展性考虑，增加部分样式配置。考虑到自定义组件复杂度，开放的意义不大，不支持增加新的timer组件

**Comment by ICMI** [comment]
#37
