### ISSUE TITLE
TypeError: Bn.measureText is not a function

### ISSUE THREAD

**Issue by SevenGuns** [antvis/F6#36]
{
  // 点集
  nodes: [
    {
      id: "1",
      label: "节点1"
      // x: 100, // Number，可选，节点位置的 x 值
      // y: 200 // Number，可选，节点位置的 y 值
    },
    {
      id: "2",
      label: "节点2"
      // x: 300, // Number，可选，节点位置的 x 值
      // y: 200 // Number，可选，节点位置的 y 值
    }
  ],
  // 边集
  edges: [
    {
      source: "1", // String，必须，起始点 id
      target: "2"
      // label: "关系"
    }
  ]
};

**Comment by SevenGuns** [comment]
wrapContext

**Comment by openwayne** [comment]
> wrapContext

具体是在哪个端？

**Comment by SevenGuns** [comment]
> > wrapContext
> 
> 具体是在哪个端？

阿里小程序

**Comment by openwayne** [comment]
> > > wrapContext
> > 
> > 
> > 具体是在哪个端？
> 
> 阿里小程序

阿里小程序中，除支付宝端外，其他端需自行注入这个函数，参考@antv/f6-alipay的做法即可

**Comment by openwayne** [comment]
建议直接使用@antv/f6-alipay 进行开发
